import {block} from './questions.js';
const $=s=>document.querySelector(s), key='your-space-draft-v1';
const words={brand:['Своя сторона','Your space'],start:['Начать','Start'],resume:['Продолжить','Continue'],next:['Дальше','Next'],back:['Назад','Back'],skip:['Пропустить','Skip'],unknown:['Не знаю','I do not know'],other:['Другое','Something else'],private:['Не хочу отвечать','I prefer not to answer'],optional:['Можно добавить своими словами — необязательно','You can add your own words — optional'],pause:['Пауза','Pause'],saved:['Прогресс хранится только в этом браузере. Ответы пока никому не отправляются.','Progress stays in this browser only. Answers are not sent to anyone yet.'],clear:['Удалить ответы с этого устройства','Delete answers from this device'],review:['Посмотреть ответы','Review answers'],skipped:['Пропущено','Skipped'],edit:['Изменить','Edit'],storage:['Браузер не даёт сохранить прогресс. Не закрывай страницу до выгрузки ответов.','This browser cannot save progress. Keep this page open until you download your answers.']};
let state={lang:'ru',screen:'welcome',index:0,answers:{},consent:false},storageOK=true;
try{const x=JSON.parse(localStorage.getItem(key));if(x&&['ru','en'].includes(x.lang)&&x.answers&&typeof x.answers==='object')state={...state,...x,screen:['welcome','question','review','done'].includes(x.screen)?x.screen:'welcome',index:Math.max(0,Math.min(5,Number(x.index)||0))};}catch{storageOK=false;}
const tr=x=>x[state.lang==='en'?1:0],w=k=>tr(words[k]);
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const t=(ru,en)=>tr([ru,en]);
function save(){try{localStorage.setItem(key,JSON.stringify(state));storageOK=true;}catch{storageOK=false;}}
function go(screen){state.screen=screen;save();render();window.scrollTo(0,0);$('#heading')?.focus();}
function base(){document.documentElement.lang=state.lang;document.title=w('brand');$('#brand').textContent=w('brand');document.querySelectorAll('[data-lang]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.lang===state.lang)));$('#footer').innerHTML=`${esc(w('saved'))}<br><button class="quiet" id="erase">${esc(w('clear'))}</button>`;$('#erase').onclick=()=>{if(confirm(t('Удалить сохранённые здесь ответы? Уже скачанные файлы останутся.','Delete answers saved here? Files already downloaded will stay.'))){state={lang:state.lang,screen:'welcome',index:0,answers:{},consent:false};save();render();}};}
function render(){base();let html='';if(state.screen==='welcome')html=`<div class="eyebrow">${t('Блок 01 · Знакомство','Set 01 · A first look')}</div><h1 id="heading" tabindex="-1">${t('Что интересно<br>именно тебе?','What interests<br>you?')}</h1><p class="intro">${t('Несколько коротких вопросов о занятиях и о том, как тебе удобнее отвечать. Здесь нет правильных ответов.','A few short questions about activities and how you prefer to answer. There are no right answers.')}</p><div class="meta"><span class="pill">${t('6 вопросов','6 questions')}</span><span class="pill">${t('Около 3 минут','About 3 minutes')}</span><span class="pill">${t('Без таймера','No timer')}</span></div><div class="note"><p>${t('Дмитрий помог сделать этот сайт. Если ты передашь ему ответы, он сможет обсудить их с ИИ и подготовить следующий блок. Это не медицинский тест.','Dzmitry helped make this site. If you share your answers with him, he can discuss them with AI and prepare the next set. This is not a medical test.')}</p></div><p class="small">${t('Сейчас ответы сохраняются только на этом устройстве. В конце ты сможешь проверить их и скачать файл для Дмитрия. Можно пропустить любой вопрос или остановиться.','For now, answers stay on this device. At the end, you can check them and download a file for Dzmitry. You can skip any question or stop.')}</p><label class="check"><input id="consent" type="checkbox" ${state.consent?'checked':''}><span>${t('Я понимаю, как будут использоваться ответы, и хочу попробовать.','I understand how my answers may be used and I want to try.')}</span></label><button id="start" class="primary wide" ${state.consent?'':'disabled'}>${Object.keys(state.answers).length?w('resume'):w('start')} →</button>`;
if(state.screen==='question'){const q=block.questions[state.index],a=state.answers[q.id]||{values:[],text:''};const opts=[...q.options.map(o=>[o[0],tr(o.slice(1))]),['other',w('other')],['unknown',w('unknown')],['private',w('private')]];html=`<div class="progress-head"><span>${state.index+1} / ${block.questions.length}</span><button id="pause" class="quiet">${w('pause')}</button></div><progress value="${state.index}" max="6" aria-label="${t('Прогресс','Progress')}"></progress><h1 id="heading" tabindex="-1">${esc(tr(q.title))}</h1>${q.hint?`<p>${esc(tr(q.hint))}</p>`:''}<fieldset class="choices" style="border:0;padding:0" aria-labelledby="heading">${opts.map(([v,label])=>`<label class="choice ${['unknown','private'].includes(v)?'muted-choice':''}"><input type="${q.type==='multi'?'checkbox':'radio'}" name="answer" value="${v}" ${a.values.includes(v)?'checked':''}><span>${esc(label)}</span></label>`).join('')}</fieldset><label class="small" for="note">${w('optional')}</label><textarea id="note" maxlength="1200" placeholder="${t('Если хочется добавить…','If you would like to add something…')}">${esc(a.text)}</textarea><div class="actions"><button id="back" class="secondary">${w('back')}</button><button id="next" class="primary">${state.index===5?w('review'):w('next')} →</button></div><button id="skip" class="quiet wide">${w('skip')}</button>`;}
if(state.screen==='review')html=`<div class="eyebrow">${t('Без оценок и баллов','No scores or grades')}</div><h1 id="heading" tabindex="-1">${t('Всё так?','Does this look right?')}</h1><p>${t('Это твои ответы, без выводов о тебе. Можно изменить любой из них.','These are your answers, with no conclusions about you. You can change any of them.')}</p>${block.questions.map((q,i)=>{const a=state.answers[q.id];return `<section class="review-item"><h2>${esc(tr(q.title))}</h2><p>${esc(!a||a.skipped?w('skipped'):a.values.map(v=>{const o=q.options.find(x=>x[0]===v);return o?tr(o.slice(1)):words[v]?w(v):v;}).join(' · ')||t('Только свой ответ','My own answer'))}</p>${a?.text?`<p>${esc(a.text)}</p>`:''}<button class="quiet edit" data-index="${i}">${w('edit')}</button></section>`;}).join('')}<div class="actions"><button id="finish" class="primary">${t('Завершить блок','Finish this set')} →</button></div>`;
if(state.screen==='done')html=`<div class="success-mark">✓</div><div class="eyebrow">${t('Блок завершён','Set complete')}</div><h1 id="heading" tabindex="-1">${t('На сегодня достаточно.','That is enough for today.')}</h1><p>${t('Спасибо, что попробовал. Если хочешь поделиться ответами, скачай файл и передай его Дмитрию удобным способом. Автоматически ничего не отправлено.','Thanks for trying this. If you want to share your answers, download the file and send it to Dzmitry in a way that works for you. Nothing has been sent automatically.')}</p><button id="download" class="primary wide">${t('Скачать мои ответы','Download my answers')} ↓</button><p class="small">${t('Файл содержит твои ответы обычным текстом. Передавай его только тому, кому хочешь их показать.','The file contains your answers as plain text. Only share it with someone you want to read them.')}</p><button id="review" class="secondary wide">${w('review')}</button><p id="download-status" role="status"></p>`;
$('#app').innerHTML=html+(!storageOK?`<p class="error" role="status">${w('storage')}</p>`:'');bind();}
function current(){const q=block.questions[state.index];return state.answers[q.id]??={values:[],text:'',skipped:false};}
function bind(){if(state.screen==='welcome'){$('#consent').onchange=e=>{state.consent=e.target.checked;save();$('#start').disabled=!state.consent;};$('#start').onclick=()=>{if(state.consent)go('question');};}
if(state.screen==='question'){$('#pause').onclick=()=>go('welcome');$('#back').onclick=()=>{if(state.index===0)go('welcome');else{state.index--;go('question');}};document.querySelectorAll('[name=answer]').forEach(input=>input.onchange=()=>{const a=current(),exclusive=['unknown','private'];if(block.questions[state.index].type==='single')a.values=[input.value];else if(exclusive.includes(input.value)&&input.checked)a.values=[input.value];else{a.values=[...document.querySelectorAll('[name=answer]:checked')].map(x=>x.value).filter(x=>!exclusive.includes(x));}a.skipped=false;document.querySelectorAll('[name=answer]').forEach(x=>x.checked=a.values.includes(x.value));save();});$('#note').oninput=e=>{current().text=e.target.value;current().skipped=false;save();};const advance=()=>{if(state.index===5)go('review');else{state.index++;go('question');}};$('#next').onclick=()=>{const a=current();if(!a.values.length&&!a.text.trim())a.skipped=true;advance();};$('#skip').onclick=()=>{state.answers[block.questions[state.index].id]={values:[],text:'',skipped:true};advance();};}
if(state.screen==='review'){document.querySelectorAll('.edit').forEach(b=>b.onclick=()=>{state.index=Number(b.dataset.index);go('question');});$('#finish').onclick=()=>go('done');}
if(state.screen==='done'){$('#review').onclick=()=>go('review');$('#download').onclick=()=>{const data={schemaVersion:1,blockId:block.id,blockVersion:block.version,language:state.lang,sharedAt:new Date().toISOString(),notice:'Participant-selected answers. Not a diagnosis. Skips are not symptoms.',answers:block.questions.map(q=>({questionId:q.id,question:q.title,...(state.answers[q.id]||{values:[],text:'',skipped:true}),options:q.options}))};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='answers-first-steps.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);$('#download-status').textContent=t('Файл подготовлен. Если браузер спросит, выбери «Сохранить».','Your file is ready. If your browser asks, choose Save.');};}}
document.querySelectorAll('[data-lang]').forEach(b=>b.onclick=()=>{state.lang=b.dataset.lang;save();render();});render();
