export const block = {
 id:'first-steps-v1',version:1,
 questions:[
 {id:'purpose',type:'single',title:['Что тебе хотелось бы здесь найти?','What would you like to find here?'],options:[['interests','Интересные занятия','Activities I enjoy'],['study','Идеи, чему учиться дальше','Ideas for what to study next'],['easier','Что делает обычные дела проще','What makes daily tasks easier'],['try','Просто посмотреть, что здесь','Just see what this is like']]},
 {id:'activities',type:'multi',title:['Что тебе нравится делать в свободное время?','What do you enjoy in your free time?'],hint:['Можно выбрать несколько вариантов.','You can choose more than one.'],options:[['play','Играть','Play games'],['talk','Общаться','Talk or chat with people'],['learn','Узнавать, как что-то работает','Learn how things work'],['make','Создавать что-то своё','Make something of my own'],['stories','Смотреть, читать или слушать','Watch, read or listen'],['puzzles','Решать задачи и головоломки','Solve problems and puzzles'],['active','Двигаться или заниматься спортом','Move around or play sports']]},
 {id:'engagement',type:'single',title:['Вспомни занятие, от которого недавно не хотелось отвлекаться. Что тебя удерживало?','Think of something you wanted to keep doing recently. What kept you interested?'],options:[['progress','Хотелось стать лучше или пройти дальше','I wanted to get better or reach the next step'],['curiosity','Хотелось узнать, что будет дальше','I wanted to find out what came next'],['create','Нравилось придумывать или создавать','I enjoyed making something'],['people','Было интересно с другими людьми','I enjoyed being with other people'],['familiar','Было приятно заниматься знакомым делом','It felt good to do something familiar'],['none','Не вспоминается такое занятие','I cannot think of an activity like that']]},
 {id:'choice',type:'single',title:['Какое маленькое задание ты бы выбрал?','Which small activity would you choose?'],hint:['Это только выбор. Выполнять сейчас не нужно.','Just choose. You do not have to do it now.'],options:[['explain','Объяснить новичку правила любимой игры','Explain a favourite game to a new player'],['pattern','Найти правило в головоломке','Find a pattern in a puzzle'],['design','Придумать новую игровую возможность','Think of a new feature for a game'],['compare','Сравнить варианты и выбрать подходящий','Compare options and choose one'],['story','Придумать короткую историю','Make up a short story'],['none','Ни одно из этих','None of these']]},
 {id:'format',type:'single',title:['Как тебе удобнее отвечать?','How do you prefer to answer?'],options:[['choices','Выбирать из вариантов','Choose from a list'],['write','Писать своими словами','Write in my own words'],['mix','Иногда выбирать, иногда писать','Sometimes choose, sometimes write'],['depends','Зависит от вопроса','It depends on the question']]},
 {id:'length',type:'single',title:['Какой длины сделать следующий блок?','How long should the next set be?'],options:[['short','Короче: 2–3 вопроса','Shorter: 2–3 questions'],['same','Примерно столько же: 5–6','About the same: 5–6'],['long','Можно немного больше: 7–8','A little longer: 7–8'],['stop','Пока не хочу следующий блок','I do not want another set for now']]}
 ]
};
