export const firstBlock = {
 id:'first-steps-v1',version:1,
 questions:[
 {id:'purpose',type:'single',title:['Что тебе хотелось бы здесь найти?','What would you like to find here?'],options:[['interests','Интересные занятия','Activities I enjoy'],['study','Идеи, чему учиться дальше','Ideas for what to study next'],['easier','Что делает обычные дела проще','What makes daily tasks easier'],['try','Просто посмотреть, что здесь','Just see what this is like']]},
 {id:'activities',type:'multi',title:['Что тебе нравится делать в свободное время?','What do you enjoy in your free time?'],hint:['Можно выбрать несколько вариантов.','You can choose more than one.'],options:[['play','Играть','Play games'],['talk','Общаться','Talk or chat with people'],['learn','Узнавать, как что-то работает','Learn how things work'],['make','Создавать что-то своё','Make something of my own'],['stories','Смотреть, читать или слушать','Watch, read or listen'],['puzzles','Решать задачи и головоломки','Solve problems and puzzles'],['active','Двигаться или заниматься спортом','Move around or play sports']]},
 {id:'engagement',type:'single',title:['Вспомни занятие, от которого недавно не хотелось отвлекаться. Что тебя удерживало?','Think of something you wanted to keep doing recently. What kept you interested?'],options:[['progress','Хотелось стать лучше или пройти дальше','I wanted to get better or reach the next step'],['curiosity','Хотелось узнать, что будет дальше','I wanted to find out what came next'],['create','Нравилось придумывать или создавать','I enjoyed making something'],['people','Было интересно с другими людьми','I enjoyed being with other people'],['familiar','Было приятно заниматься знакомым делом','It felt good to do something familiar'],['none','Не вспоминается такое занятие','I cannot think of an activity like that']]},
 {id:'choice',type:'single',title:['Какое маленькое задание ты бы выбрал?','Which small activity would you choose?'],hint:['Это только выбор. Выполнять сейчас не нужно.','Just choose. You do not have to do it now.'],options:[['explain','Объяснить новичку правила любимой игры','Explain a favourite game to a new player'],['pattern','Найти правило в головоломке','Find a pattern in a puzzle'],['design','Придумать новую игровую возможность','Think of a new feature for a game'],['compare','Сравнить варианты и выбрать подходящий','Compare options and choose one'],['story','Придумать короткую историю','Make up a short story'],['none','Ни одно из этих','None of these']]},
 {id:'format',type:'single',title:['Как тебе удобнее отвечать?','How do you prefer to answer?'],options:[['choices','Выбирать из вариантов','Choose from a list'],['write','Писать своими словами','Write in my own words'],['mix','Иногда выбирать, иногда писать','Sometimes choose, sometimes write'],['depends','Зависит от вопроса','It depends on the question']]},
 {id:'length',type:'single',title:['Какой длины сделать следующий блок?','How long should the next set be?'],options:[['short','Короче: 2–3 вопроса','Shorter: 2–3 questions'],['same','Примерно столько же: 5–6','About the same: 5–6'],['long','Можно немного больше: 7–8','A little longer: 7–8'],['stop','Пока не хочу следующий блок','I do not want another set for now']]}
 ]
};

export const secondBlock = {
 id:'interests-details-v1',version:1,
 label:['Блок 02 · Чуть подробнее','Set 02 · A closer look'],
 title:['Что тебе нравится<br>в занятиях?','What do you enjoy<br>about activities?'],
 intro:['Четыре вопроса об играх и о том, как тебе удобнее объяснять. Можно вспомнить один недавний пример.','Four questions about games and how you prefer to explain things. You can think of one recent example.'],
 questions:[
 {id:'game_actions',type:'multi',title:['Вспомни игру, в которую недавно играл. Что тебе в ней нравилось делать?','Think of a game you played recently. What did you enjoy doing?'],hint:['Можно выбрать несколько вариантов. Если хочется, ниже можно написать название игры.','You can choose more than one. If you want, you can write the name of the game below.'],options:[['explore','Исследовать места и находить новое','Explore places and find new things'],['solve','Разбираться, как пройти сложное место','Work out how to get past a difficult part'],['build','Строить, создавать или менять что-то','Build, create or change things'],['improve','Тренироваться и улучшать результат','Practise and improve my results'],['together','Делать что-то вместе с другими','Do things with other people'],['story','Следить за историей и персонажами','Follow the story and characters'],['none','Ничего из этого / давно не играл','None of these / I have not played recently']]},
 {id:'recent_curiosity',type:'multi',title:['Вспомни момент, когда хотелось узнать, что будет дальше. Что именно было интересно?','Think of a time when you wanted to find out what came next. What were you curious about?'],hint:['Это может быть игра, видео, книга или другое занятие. Можно выбрать несколько вариантов.','It could be a game, a video, a book or another activity. You can choose more than one.'],options:[['story','Чем закончится история или событие','How a story or event would end'],['unlock','Что откроется на следующем этапе','What I would find at the next stage'],['experiment','Что получится, если попробовать другой способ','What would happen if I tried a different way'],['reason','Почему что-то устроено или работает именно так','Why something works the way it does'],['people','Что придумают или сделают другие','What other people would think of or do'],['none','Не могу вспомнить такой момент','I cannot think of a moment like that']]},
 {id:'explain_channel',type:'single',title:['Если бы ты решил объяснить новичку знакомую игру, какой способ выбрал бы?','If you decided to explain a game you know to a new player, how would you do it?'],hint:['Представь удобный для себя вариант. Объяснять сейчас не нужно.','Imagine a way that suits you. You do not need to explain anything now.'],options:[['text','Переписываться сообщениями','Exchange text messages'],['voice','Поговорить в голосовом чате','Talk in a voice chat'],['together','Поиграть вместе и показывать по ходу','Play together and show them as we go'],['guide','Заранее сделать текст или видео с объяснением','Prepare a written guide or a video'],['inperson','Объяснить при встрече рядом с человеком','Explain in person, sitting near them'],['depends','Зависит от человека или игры','It depends on the person or the game'],['decline','Сейчас не хотел бы объяснять','I would not want to explain right now']]},
 {id:'explain_content',type:'single',title:['Что ты показал бы или объяснил первым?','What would you show or explain first?'],hint:['В той же игре. Здесь нет правильного порядка.','Think of the same game. There is no right order.'],options:[['goal','Какова цель игры','The aim of the game'],['controls','Какие кнопки нажимать и как управлять','Which buttons to press and how to control things'],['example','Один простой пример: «Смотри, я делаю так»','One simple example: “Look, this is what I do”'],['fun','Что в этой игре самое интересное для меня','What I enjoy most about the game'],['ask','Сначала спросил бы, что человек уже знает','I would first ask what they already know'],['depends','Зависит от того, с чем нужна помощь','It depends on what they need help with'],['decline','Не хотел бы объяснять','I would not want to explain']]}
 ]
};
export const block = {
 id:'daily-experiences-v1',version:1,
 label:['Блок 03 · Занятия и планы','Set 03 · Activities and plans'],
 title:['Вспомним несколько<br>обычных ситуаций','Think about a few<br>everyday moments'],
 intro:['Четыре вопроса о занятиях вне игр и об одном случае изменения планов. Можно пропустить вопрос, если подходящий пример не вспоминается.','Four questions about activities outside games and one change of plans. You can skip a question if you cannot think of an example.'],
 questions:[
 {id:'outside_activity',type:'single',title:['Вспомни одно занятие вне игр за последнюю неделю, которое тебе было интересно. Что это было?','Think of one activity outside games that interested you in the past week. What was it?'],hint:['Выбери один пример для следующих двух вопросов. Можно написать о нём ниже, но это необязательно.','Choose one example for the next two questions. You can write about it below, but you do not have to.'],options:[['watch_read','Смотрел или читал о чём-то интересном','Watched or read about something interesting'],['make','Создавал, собирал или настраивал что-то','Made, put together or set up something'],['learn','Изучал тему или решал задачу','Studied a topic or solved a problem'],['creative','Рисовал, писал или занимался музыкой','Drew, wrote or did something with music'],['people','Занимался чем-то с другими людьми','Did an activity with other people'],['physical','Готовил, гулял или занимался физической активностью','Cooked, went for a walk or did a physical activity'],['no_example','Не вспоминается такого занятия','I cannot think of an activity like that']]},
 {id:'activity_source',type:'single',title:['Как ты выбрал это занятие?','How did you choose that activity?'],hint:['Вспомни тот же пример.','Think of the same example.'],options:[['own','Сам захотел попробовать или разобраться','I wanted to try it or learn about it'],['found','Случайно увидел что-то интересное','I happened to see something interesting'],['suggested','Кто-то предложил или показал','Someone suggested it or showed it to me'],['task','Это было задание или просьба','It was a task or someone asked me to do it'],['usual','Это моё привычное занятие','It is something I usually do'],['no_example','Нет подходящего примера','I do not have an example']]},
 {id:'activity_start',type:'single',title:['Что ты сделал в самом начале этого занятия?','What did you do at the start of that activity?'],hint:['Как было в тот раз, а не как бывает всегда.','Think about that time, not what you always do.'],options:[['started','Сразу начал смотреть, читать или пробовать','Started watching, reading or trying it straight away'],['example','Сначала посмотрел, как это делает кто-то другой','First watched how someone else does it'],['instructions','Сначала прочитал объяснение или инструкцию','First read an explanation or instructions'],['asked','Сначала спросил кого-то','First asked someone'],['prepared','Сначала подготовил то, что нужно','First got the things I needed ready'],['later','Сначала отложил, потом вернулся','Left it for later, then came back to it'],['no_example','Нет подходящего примера','I do not have an example']]},
 {id:'changed_plan',type:'multi',title:['Вспомни последний раз, когда твои планы неожиданно изменились. Что было после этого?','Think of the last time your plans changed unexpectedly. What happened after that?'],hint:['Можно выбрать несколько вариантов. Этот случай не обязательно связан с предыдущим занятием.','You can choose more than one. This does not have to be about the activity in the earlier questions.'],options:[['switched','Спокойно перешёл к другому делу','Moved on to something else without a problem'],['time','Понадобилось время, прежде чем решить, что делать','Needed some time before deciding what to do'],['clarify','Хотел сначала узнать, какой теперь план','Wanted to know the new plan first'],['upset','Расстроился или разозлился','Felt upset or angry'],['relief','Обрадовался изменению или почувствовал облегчение','Felt happy about the change or relieved'],['kept','Попробовал всё-таки сделать то, что планировал','Tried to do what I had planned anyway'],['no_example','Не вспоминается такого случая','I cannot think of a time like that']]}
 ]
};
export const blocks = [firstBlock,secondBlock,block];
