export const firstBlock = {
 id:'first-steps-v1',version:1,
 questions:[
 {id:'purpose',type:'single',title:['Что тебе хотелось бы здесь найти?','What would you like to find here?'],options:[['interests','Интересные занятия','Activities I enjoy'],['study','Идеи, чему учиться дальше','Ideas for what to study next'],['easier','Что делает обычные дела проще','What makes daily tasks easier'],['try','Просто посмотреть, что здесь','Just see what this is like']]},
 {id:'activities',type:'multi',title:['Что тебе нравится делать в свободное время?','What do you enjoy in your free time?'],hint:['Можно выбрать несколько вариантов.','You can choose more than one.'],options:[['play','Играть','Play games'],['talk','Общаться','Talk or chat with people'],['learn','Узнавать, как что-то работает','Learn how things work'],['make','Создавать что-то своё','Make something of my own'],['stories','Смотреть, читать или слушать','Watch, read or listen'],['puzzles','Решать задачи и головоломки','Solve problems and puzzles'],['active','Двигаться или заниматься спортом','Move around or play sports']]},
 {id:'engagement',type:'single',title:['Вспомни занятие, от которого недавно не хотелось отвлекаться. Что тебя удерживало?','Think of something you wanted to keep doing recently. What kept you interested?'],options:[['progress','Хотелось стать лучше или пройти дальше','I wanted to get better or reach the next step'],['curiosity','Хотелось узнать, что будет дальше','I wanted to find out what came next'],['create','Нравилось придумывать или создавать','I enjoyed making something'],['people','Было интересно с другими людьми','I enjoyed being with other people'],['familiar','Было приятно заниматься знакомым делом','It felt good to do something familiar'],['none','Не вспоминается такое занятие','I cannot think of an activity like that']]},
 {id:'choice',type:'single',title:['Какое маленькое задание ты бы выбрал?','Which small activity would you choose?'],hint:['Это только выбор. Выполнять сейчас не нужно.','Just choose. You do not have to do it now.'],options:[['explain','Объяснить новичку правила любимой игры','Explain a favourite game to a new player'],['pattern','Найти правило в головоломке','Find a pattern in a puzzle'],['design','Придумать новую игровую возможность','Think of a new feature for a game'],['compare','Сравнить варианты и выбрать подходящий','Compare options and choose one'],['story','Придумать короткую историю','Make up a short story'],['none','Ни одно из этих','None of these']]},
 {id:'format',type:'single',title:['Как тебе удобнее отвечать?','How do you prefer to answer?'],options:[['choices','Выбирать из вариантов','Choose from a list'],['write','Писать своими словами','Write in my own words'],['mix','Иногда выбирать, иногда писать','Sometimes choose, sometimes write'],['depends','Зависит от вопроса','It depends on the question']]},
 {id:'length',type:'single',title:['Какой длины сделать следующий блок?','How long should the next set be?'],options:[['short','Короче: 2–3 вопроса','Shorter: 2–3 questions'],['same','Примерно столько же: 5–6','About the same: 5–6'],['long','Можно немного больше: 7–8','A little longer: 7–8'],['stop','Пока не хочу следующий блок','I do not want another set for now']]}
 ]
};

export const secondBlock = {
 id:'interests-details-v1',version:1,
 label:['Блок 02 · Чуть подробнее','Set 02 · A closer look'],
 title:['Что тебе нравится<br>в занятиях?','What do you enjoy<br>about activities?'],
 intro:['Четыре вопроса об играх и о том, как тебе удобнее объяснять. Можно вспомнить один недавний пример.','Four questions about games and how you prefer to explain things. You can think of one recent example.'],
 questions:[
 {id:'game_actions',type:'multi',title:['Вспомни игру, в которую недавно играл. Что тебе в ней нравилось делать?','Think of a game you played recently. What did you enjoy doing?'],hint:['Можно выбрать несколько вариантов. Если хочется, ниже можно написать название игры.','You can choose more than one. If you want, you can write the name of the game below.'],options:[['explore','Исследовать места и находить новое','Explore places and find new things'],['solve','Разбираться, как пройти сложное место','Work out how to get past a difficult part'],['build','Строить, создавать или менять что-то','Build, create or change things'],['improve','Тренироваться и улучшать результат','Practise and improve my results'],['together','Делать что-то вместе с другими','Do things with other people'],['story','Следить за историей и персонажами','Follow the story and characters'],['none','Ничего из этого / давно не играл','None of these / I have not played recently']]},
 {id:'recent_curiosity',type:'multi',title:['Вспомни момент, когда хотелось узнать, что будет дальше. Что именно было интересно?','Think of a time when you wanted to find out what came next. What were you curious about?'],hint:['Это может быть игра, видео, книга или другое занятие. Можно выбрать несколько вариантов.','It could be a game, a video, a book or another activity. You can choose more than one.'],options:[['story','Чем закончится история или событие','How a story or event would end'],['unlock','Что откроется на следующем этапе','What I would find at the next stage'],['experiment','Что получится, если попробовать другой способ','What would happen if I tried a different way'],['reason','Почему что-то устроено или работает именно так','Why something works the way it does'],['people','Что придумают или сделают другие','What other people would think of or do'],['none','Не могу вспомнить такой момент','I cannot think of a moment like that']]},
 {id:'explain_channel',type:'single',title:['Если бы ты решил объяснить новичку знакомую игру, какой способ выбрал бы?','If you decided to explain a game you know to a new player, how would you do it?'],hint:['Представь удобный для себя вариант. Объяснять сейчас не нужно.','Imagine a way that suits you. You do not need to explain anything now.'],options:[['text','Переписываться сообщениями','Exchange text messages'],['voice','Поговорить в голосовом чате','Talk in a voice chat'],['together','Поиграть вместе и показывать по ходу','Play together and show them as we go'],['guide','Заранее сделать текст или видео с объяснением','Prepare a written guide or a video'],['inperson','Объяснить при встрече рядом с человеком','Explain in person, sitting near them'],['depends','Зависит от человека или игры','It depends on the person or the game'],['decline','Сейчас не хотел бы объяснять','I would not want to explain right now']]},
 {id:'explain_content',type:'single',title:['Что ты показал бы или объяснил первым?','What would you show or explain first?'],hint:['В той же игре. Здесь нет правильного порядка.','Think of the same game. There is no right order.'],options:[['goal','Какова цель игры','The aim of the game'],['controls','Какие кнопки нажимать и как управлять','Which buttons to press and how to control things'],['example','Один простой пример: «Смотри, я делаю так»','One simple example: “Look, this is what I do”'],['fun','Что в этой игре самое интересное для меня','What I enjoy most about the game'],['ask','Сначала спросил бы, что человек уже знает','I would first ask what they already know'],['depends','Зависит от того, с чем нужна помощь','It depends on what they need help with'],['decline','Не хотел бы объяснять','I would not want to explain']]}
 ]
};
export const thirdBlock = {
 id:'daily-experiences-v1',version:1,
 label:['Блок 03 · Занятия и планы','Set 03 · Activities and plans'],
 title:['Вспомним несколько<br>обычных ситуаций','Think about a few<br>everyday moments'],
 intro:['Четыре вопроса о занятиях вне игр и об одном случае изменения планов. Можно пропустить вопрос, если подходящий пример не вспоминается.','Four questions about activities outside games and one change of plans. You can skip a question if you cannot think of an example.'],
 questions:[
 {id:'outside_activity',type:'single',title:['Вспомни одно занятие вне игр за последнюю неделю, которое тебе было интересно. Что это было?','Think of one activity outside games that interested you in the past week. What was it?'],hint:['Выбери один пример для следующих двух вопросов. Можно написать о нём ниже, но это необязательно.','Choose one example for the next two questions. You can write about it below, but you do not have to.'],options:[['watch_read','Смотрел или читал о чём-то интересном','Watched or read about something interesting'],['make','Создавал, собирал или настраивал что-то','Made, put together or set up something'],['learn','Изучал тему или решал задачу','Studied a topic or solved a problem'],['creative','Рисовал, писал или занимался музыкой','Drew, wrote or did something with music'],['people','Занимался чем-то с другими людьми','Did an activity with other people'],['physical','Готовил, гулял или занимался физической активностью','Cooked, went for a walk or did a physical activity'],['no_example','Не вспоминается такого занятия','I cannot think of an activity like that']]},
 {id:'activity_source',type:'single',title:['Как ты выбрал это занятие?','How did you choose that activity?'],hint:['Вспомни тот же пример.','Think of the same example.'],options:[['own','Сам захотел попробовать или разобраться','I wanted to try it or learn about it'],['found','Случайно увидел что-то интересное','I happened to see something interesting'],['suggested','Кто-то предложил или показал','Someone suggested it or showed it to me'],['task','Это было задание или просьба','It was a task or someone asked me to do it'],['usual','Это моё привычное занятие','It is something I usually do'],['no_example','Нет подходящего примера','I do not have an example']]},
 {id:'activity_start',type:'single',title:['Что ты сделал в самом начале этого занятия?','What did you do at the start of that activity?'],hint:['Как было в тот раз, а не как бывает всегда.','Think about that time, not what you always do.'],options:[['started','Сразу начал смотреть, читать или пробовать','Started watching, reading or trying it straight away'],['example','Сначала посмотрел, как это делает кто-то другой','First watched how someone else does it'],['instructions','Сначала прочитал объяснение или инструкцию','First read an explanation or instructions'],['asked','Сначала спросил кого-то','First asked someone'],['prepared','Сначала подготовил то, что нужно','First got the things I needed ready'],['later','Сначала отложил, потом вернулся','Left it for later, then came back to it'],['no_example','Нет подходящего примера','I do not have an example']]},
 {id:'changed_plan',type:'multi',title:['Вспомни последний раз, когда твои планы неожиданно изменились. Что было после этого?','Think of the last time your plans changed unexpectedly. What happened after that?'],hint:['Можно выбрать несколько вариантов. Этот случай не обязательно связан с предыдущим занятием.','You can choose more than one. This does not have to be about the activity in the earlier questions.'],options:[['switched','Спокойно перешёл к другому делу','Moved on to something else without a problem'],['time','Понадобилось время, прежде чем решить, что делать','Needed some time before deciding what to do'],['clarify','Хотел сначала узнать, какой теперь план','Wanted to know the new plan first'],['upset','Расстроился или разозлился','Felt upset or angry'],['relief','Обрадовался изменению или почувствовал облегчение','Felt happy about the change or relieved'],['kept','Попробовал всё-таки сделать то, что планировал','Tried to do what I had planned anyway'],['no_example','Не вспоминается такого случая','I cannot think of a time like that']]}
 ]
};
export const fourthBlock = {
 id:'content-and-clarity-v1',version:1,
 label:['Блок 04 · Что интересно и что понятно','Set 04 · Interests and understanding'],
 title:['Что хочется<br>узнать подробнее?','What would you like<br>to learn more about?'],
 intro:['Четыре вопроса о том, что ты смотришь или читаешь, и об изменении планов. Можно выбрать готовые ответы или пропустить вопрос.','Four questions about what you watch or read, and about a change of plans. You can choose answers or skip a question.'],
 questions:[
 {id:'content_topics',type:'multi',title:['О чём тебе было интересно смотреть или читать в последнее время?','What have you enjoyed watching or reading about recently?'],hint:['Можно выбрать несколько тем. Материалы об играх тоже подходят.','You can choose more than one topic. Content about games counts too.'],options:[['games','Игры и игровые миры','Games and game worlds'],['tech','Компьютеры, техника или программы','Computers, technology or software'],['science','Природа, космос или научные вопросы','Nature, space or science'],['history','История, страны или события','History, countries or events'],['people','Люди, их жизнь или отношения','People, their lives or relationships'],['arts','Музыка, кино, рисунки или другие творческие работы','Music, films, drawings or other creative work'],['language','Языки, слова или общение на другом языке','Languages, words or communication in another language'],['everyday','Спорт, еда или другие повседневные занятия','Sport, food or other everyday activities']]},
 {id:'content_kind',type:'single',title:['Вспомни один материал, который недавно понравился. Что в нём было?','Think of one thing you watched or read recently and liked. What did it contain?'],hint:['Например, видео, статья, пост или книга. Название можно написать ниже, если хочется.','For example, a video, an article, a post or a book. You can write the title below if you want.'],options:[['explanation','Объяснение, как или почему что-то работает','An explanation of how or why something works'],['events','Рассказ о реальных событиях или фактах','An account of real events or facts'],['story','Придуманная история и персонажи','A fictional story and characters'],['instructions','Показ или инструкция, как что-то сделать','A demonstration or instructions for doing something'],['opinion','Мнение, обсуждение или сравнение','An opinion, a discussion or a comparison'],['entertainment','Что-то смешное или просто приятное для просмотра','Something funny or simply enjoyable to watch'],['mixed','Сразу несколько из этих вариантов','A mix of these'],['no_example','Не вспоминается подходящий материал','I cannot think of an example']]},
 {id:'unclear_content',type:'single',title:['Вспомни последний раз, когда в интересном видео или тексте что-то было непонятно. Что ты сделал сначала?','Think of the last time something in an interesting video or text was unclear. What did you do first?'],hint:['Если такого случая не вспоминается, так и можно ответить.','If you cannot remember a time like that, you can say so.'],options:[['again','Посмотрел или прочитал этот момент ещё раз','Watched or read that part again'],['another','Поискал другое объяснение','Looked for another explanation'],['try','Попробовал разобраться сам или проверить на практике','Tried to work it out myself or test it'],['ask','Спросил кого-то','Asked someone'],['continue','Продолжил: можно было понять и без этого','Kept going: I could follow it without that detail'],['leave','Отложил или выбрал что-то другое','Left it for later or chose something else'],['no_example','Не вспоминается такого случая','I cannot remember a time like that']]},
 {id:'new_plan_details',type:'multi',title:['Когда планы неожиданно изменились, что тебе хотелось узнать о новом плане?','When plans changed unexpectedly, what did you want to know about the new plan?'],hint:['Вспомни конкретный случай. Можно выбрать несколько ответов, в том числе что уточнять ничего не хотелось.','Think of a particular time. You can choose more than one answer, including that you did not need any details.'],options:[['what','Что теперь нужно делать','What I needed to do next'],['when','Когда это начнётся и сколько займёт времени','When it would start and how long it would take'],['where','Где это будет','Where it would happen'],['who','Кто будет рядом или участвовать','Who would be there or take part'],['why','Почему всё изменилось','Why the plan changed'],['choice','Можно ли выбрать другой вариант','Whether I could choose another option'],['nothing','Ничего: информации уже хватало','Nothing: I already had enough information'],['no_example','Не вспоминается такого случая','I cannot remember a time like that']]}
 ]
};
export const fifthBlock = {
 id:'follow-up-examples-v1',version:1,
 label:['Блок 05 · Вернёмся к примерам','Set 05 · Back to the examples'],
 title:['Ещё немного<br>о тех же примерах','A little more<br>about the same examples'],
 intro:['Четыре уточняющих вопроса. Когда мы говорим о материале, имеется в виду то видео, текст или другой материал, который ты вспоминал в блоке 04. Если не помнишь его, так и можно ответить.','Four follow-up questions. When we say “the content”, we mean the video, text or other content you thought about in set 04. If you do not remember it, you can say so.'],
 questions:[
 {id:'tech_interest',type:'multi',title:['Что именно тебе интересно в компьютерах, технике или программах?','What interests you about computers, technology or software?'],hint:['Можно выбрать несколько вариантов. Этот вопрос не обязательно о материале из прошлого блока.','You can choose more than one answer. This question does not have to be about the content from the last set.'],options:[['devices','Устройства, их возможности и различия','Devices, what they can do and how they differ'],['setup','Как настраивать программы и пользоваться ими','How to set up and use software'],['code','Как писать программы или делать свои проекты','How to write programs or make my own projects'],['inside','Как техника или программы устроены внутри','How devices or software work inside'],['fix','Как находить и исправлять неполадки','How to find and fix problems'],['games','То, что связано с играми: настройки, моды, игровые инструменты','Things related to games: settings, mods or tools'],['news','Новинки и новости о технологиях','New products and technology news'],['no_detail','Пока не могу выделить что-то конкретное','I cannot name anything specific yet']]},
 {id:'material_appeal',type:'multi',title:['Что тебе понравилось именно в том материале из блока 04?','What did you like about that particular content from set 04?'],hint:['Речь о том видео, тексте или другом материале, который ты вспоминал в предыдущем блоке, выбирая «Мнение, обсуждение или сравнение». Не нужно выбирать новый пример. Можно отметить несколько вариантов.','This is the video, text or other content you thought about in the last set when choosing “An opinion, a discussion or a comparison”. You do not need a new example. You can choose more than one answer.'],options:[['opinion','Было интересно узнать мнение автора','It was interesting to hear the author’s opinion'],['discussion','Было интересно увидеть разные мнения','It was interesting to see different opinions'],['comparison','Понравилось сравнение вариантов','I liked the comparison of options'],['reasons','Понравилось, как автор объяснил свою позицию','I liked how the author explained their view'],['topic','Была интересна сама тема','The topic itself was interesting'],['presentation','Понравилось, как материал был подан','I liked the way it was presented'],['forgot','Не помню, какой материал тогда вспоминал','I do not remember which content I was thinking of']]},
 {id:'repeat_result',type:'single',title:['После повторного просмотра или чтения стало понятнее?','Did watching or reading it again make it clearer?'],hint:['В блоке 04 был отдельный вопрос о непонятном моменте. Вспомни именно тот случай, когда ты посмотрел или прочитал ещё раз. Это мог быть другой материал, чем в предыдущем вопросе.','Set 04 had a separate question about an unclear part. Think of that time when you watched or read it again. It may have been different content from the previous question.'],options:[['clear','Да, стало понятно','Yes, I understood it'],['partly','Часть стала понятнее, но вопросы остались','Some of it became clearer, but I still had questions'],['same','Нет, понятнее не стало','No, it did not become clearer'],['unneeded','Оказалось, что этот момент не нужен для остального','It turned out I did not need that part to follow the rest'],['forgot','Не помню этот случай или результат','I do not remember that time or the result']]},
 {id:'plan_after_details',type:'single',title:['Когда ты узнал подробности нового плана, что было дальше?','After you learned the details of the new plan, what happened next?'],hint:['Речь о случае изменения планов из прошлого блока. Если подробности так и не удалось узнать или случай не вспоминается, выбери подходящий ответ.','Think of the change of plans from the last set. If you never got the details or cannot remember the situation, you can choose that answer.'],options:[['followed','Начал действовать по новому плану','Started following the new plan'],['time','Ещё понадобилось время, прежде чем что-то делать','Still needed some time before doing anything'],['questions','Понадобилось ещё что-то уточнить','Needed to ask about a few more things'],['alternative','Выбрал или предложил другой вариант','Chose or suggested another option'],['stopped','Решил пока не участвовать или не делать это','Decided not to take part or do it for now'],['no_details','Так и не узнал подробности','Never got the details'],['forgot','Не помню этот случай или что было дальше','I do not remember the situation or what happened next']]}
 ]
};
export const sixthBlock = {
 id:'hands-on-and-asking-v1',version:1,
 label:['Блок 06 · Пробовать и спрашивать','Set 06 · Trying and asking'],
 title:['Что ты пробовал<br>делать сам?','What have you tried<br>doing yourself?'],
 intro:['Три вопроса об одном недавнем деле с техникой и один — об общении. Вспоминать примеры из прошлых блоков не нужно. Если подходящего случая нет, можно так и ответить.','Three questions about one recent task with technology and one about communication. You do not need examples from earlier sets. If you do not have an example, you can say so.'],
 questions:[
 {id:'practical_task',type:'single',title:['Вспомни одно дело с компьютером, телефоном или игрой, которое ты недавно делал сам. Что это было?','Think of one thing you recently did yourself on a computer, phone or in a game. What was it?'],hint:['Выбери один случай для следующих двух вопросов. Не обязательно что-то сложное или полностью без помощи.','Choose one example for the next two questions. It does not have to be difficult or done without any help.'],options:[['settings','Менял настройки под себя','Changed settings to suit me'],['install','Устанавливал программу, дополнение или мод','Installed software, an add-on or a mod'],['fix','Пытался исправить то, что не работало','Tried to fix something that was not working'],['choose','Сравнивал устройства или программы, чтобы выбрать','Compared devices or software to make a choice'],['create','Создавал или менял что-то своё','Created or changed something of my own'],['learn_feature','Пробовал незнакомую функцию','Tried a feature I had not used before'],['no_example','Не вспоминается такого дела','I cannot think of a task like that']]},
 {id:'practical_first_step',type:'single',title:['С чего ты начал это дело?','How did you start that task?'],hint:['Речь о деле, которое ты только что выбрал. Если не выбрал пример, это тоже можно отметить.','Think of the task you just chose. If you did not choose an example, you can say so.'],options:[['knew','Уже знал, что делать, и начал','Already knew what to do and started'],['try','Попробовал разобраться по ходу','Tried to work it out as I went'],['video','Нашёл видео с примером','Found a video showing an example'],['read','Нашёл текстовую инструкцию или обсуждение','Found written instructions or a discussion'],['ask','Обратился к человеку за помощью','Asked someone for help'],['later','Сначала отложил, потом вернулся','Left it for later, then came back'],['no_example','Нет примера или не помню начало','I do not have an example or cannot remember the start']]},
 {id:'practical_result',type:'single',title:['Чем закончилось это дело на тот момент?','How did that task end at the time?'],hint:['Тот же случай. Он мог остаться незавершённым — это тоже ответ.','Think of the same example. It is fine if the task was not finished.'],options:[['done','Получилось то, что хотел','Got the result I wanted'],['partly','Получилось частично','Got part of it working'],['ongoing','Ещё продолжал разбираться','Was still working on it'],['pause','Отложил, чтобы вернуться позже','Stopped to return to it later'],['stopped','Решил не продолжать','Decided not to continue'],['changed','Выбрал другой способ или вариант','Chose another way or option'],['no_example','Нет примера или не помню результат','I do not have an example or cannot remember the result']]},
 {id:'asking_recently',type:'single',title:['Вспомни недавний случай, когда тебе хотелось что-то уточнить у человека. Как ты поступил?','Think of a recent time when you wanted to ask someone about something unclear. What did you do?'],hint:['Это может быть дома, в школе или онлайн. Случай не обязательно связан с техникой.','It could be at home, at school or online. It does not have to be about technology.'],options:[['voice','Спросил устно — лично или в голосовом чате','Asked by speaking, in person or in a voice chat'],['text','Написал сообщение','Sent a message'],['wait','Подождал удобного момента, потом спросил','Waited for a good moment, then asked'],['help','Попросил другого человека помочь спросить','Asked another person to help me ask'],['self','Нашёл ответ сам, не спрашивая','Found the answer myself without asking'],['not_asked','Хотел спросить, но так и не спросил','Wanted to ask but did not'],['unneeded','Решил, что уточнение уже не нужно','Decided I no longer needed to ask'],['no_example','Не вспоминается такого случая','I cannot remember a time like that']]}
 ]
};
export const seventhBlock = {
 id:'settings-and-timing-v1',version:1,
 label:['Блок 07 · Настройки и удобный момент','Set 07 · Settings and a good moment'],
 title:['Чуть подробнее<br>о двух ситуациях','A closer look<br>at two situations'],
 intro:['Четыре вопроса: два о настройках и два о вопросе человеку. В блоке 06 были вопросы о деле с техникой и о том, как ты что-то уточнял. Здесь можно вспомнить те же случаи. Если не помнишь, не нужно угадывать.','Four questions: two about settings and two about asking someone. Set 06 asked about a task with technology and about asking a question. You can use the same examples here. If you do not remember, you do not need to guess.'],
 questions:[
 {id:'settings_place',type:'single',title:['Где ты менял настройки в том случае из блока 06?','Where did you change the settings in the example from set 06?'],hint:['Если тот случай был не про настройки, можно это отметить. Название игры или программы можно написать ниже, но это необязательно.','If that example was not about settings, you can say so. You can write the name of the game or app below, but you do not have to.'],options:[['game','В игре','In a game'],['app','В программе или приложении','In a program or app'],['computer','В настройках самого компьютера','In the computer settings'],['phone','В настройках самого телефона','In the phone settings'],['device','На другом устройстве','On another device'],['not_settings','Тот случай был не про настройки','That example was not about settings'],['forgot','Не помню тот случай','I do not remember that example']]},
 {id:'settings_reason',type:'multi',title:['Для чего тебе хотелось изменить эти настройки?','Why did you want to change those settings?'],hint:['Тот же случай. Можно выбрать несколько причин. Если случай не вспоминается, так и можно ответить.','Think of the same example. You can choose more than one reason. If you do not remember it, you can say so.'],options:[['performance','Чтобы лучше или быстрее работало','To make it work better or faster'],['comfort','Чтобы было удобнее управлять или пользоваться','To make it easier to control or use'],['look_sound','Чтобы изображение или звук больше нравились','To make the picture or sound suit me better'],['problem','Чтобы убрать конкретную проблему','To solve a particular problem'],['try','Чтобы посмотреть, что изменится','To see what would change'],['request','Кто-то попросил это сделать','Someone asked me to do it'],['forgot','Не помню или нет подходящего примера','I do not remember or do not have an example']]},
 {id:'asking_person',type:'single',title:['Кому ты хотел задать вопрос в случае из блока 06?','Who did you want to ask in the example from set 06?'],hint:['Теперь другой случай: тот, где хотелось что-то уточнить у человека. Он не обязательно связан с настройками. Имя писать не нужно.','Now think of the other example: when you wanted to ask someone about something unclear. It does not have to be about settings. You do not need to give a name.'],options:[['family','Кому-то из семьи','Someone in my family'],['friend','Другу или знакомому','A friend or someone I know'],['teacher','Учителю или преподавателю','A teacher'],['community','Участнику онлайн-сообщества, с которым мало знаком','Someone in an online group I do not know well'],['staff','Сотруднику магазина, учреждения или поддержки','Someone working in a shop, an office or support'],['forgot','Не помню тот случай','I do not remember that example']]},
 {id:'asking_timing',type:'multi',title:['Что влияло на то, когда ты задал вопрос?','What affected when you asked your question?'],hint:['Тот же случай с человеком. Если ждал, выбери, почему. Если не ждал, это тоже есть в ответах. Можно выбрать несколько вариантов.','Think of the same person and situation. If you waited, choose why. There is also an answer for not waiting. You can choose more than one.'],options:[['busy','Ждал, когда человек освободится','Waited until the person was free'],['words','Обдумывал, как сформулировать вопрос','Thought about how to word my question'],['reaction','Волновался, как человек отреагирует','Felt worried about how the person would react'],['private','Хотел спросить без других людей рядом','Wanted to ask without other people nearby'],['channel','Ждал, когда смогу написать или поговорить удобным способом','Waited until I could message or talk in a way that suited me'],['own_task','Сначала заканчивал своё дело','Finished what I was doing first'],['straightaway','Не ждал — спросил сразу','Did not wait — asked straight away'],['forgot','Не помню, почему или когда спросил','I do not remember why or when I asked']]}
 ]
};
export const eighthBlock = {
 id:'finding-solutions-v1',version:1,
 label:['Блок 08 · Искать решение и обращаться','Set 08 · Finding solutions and asking'],
 title:['Как ты ищешь<br>подходящий способ?','How do you find<br>a way that works?'],
 intro:['Четыре вопроса о решении задач и об общении. Брать примеры из прошлых блоков не нужно. Последние два вопроса — об одном новом случае. Если такого случая не было или он не вспоминается, можно так и ответить.','Four questions about solving problems and talking to people. You do not need examples from earlier sets. The last two questions are about one new example. If it did not happen or you cannot remember, you can say so.'],
 questions:[
 {id:'task_appeal',type:'multi',title:['Что тебе бывает интересно, когда ты настраиваешь или исправляешь что-то в игре, программе или устройстве?','What do you find interesting when you change settings or fix something in a game, app or device?'],hint:['Можно выбрать несколько вариантов. Сам процесс не обязательно должен нравиться.','You can choose more than one answer. You do not have to enjoy the process itself.'],options:[['cause','Понять, почему что-то работает именно так','Understanding why something works that way'],['try','Пробовать разные варианты и сравнивать','Trying different options and comparing them'],['result','Получить результат, которым можно пользоваться','Getting a result I can use'],['learn','Освоить то, чего раньше не умел','Learning to do something new'],['none','Само занятие не интересно, просто нужно сделать','The activity itself is not interesting; I just need to get it done'],['no_example','Не вспоминается такого занятия','I cannot think of an activity like that']]},
 {id:'unfamiliar_start',type:'single',title:['Вспомни недавнее дело, в котором ты сначала не знал, как что-то сделать. Что ты сделал первым?','Think of a recent task where you did not know how to do something at first. What did you do first?'],hint:['Это может быть игра, учёба или обычное дело. Если хочется, напиши ниже, что это было.','It could be a game, schoolwork or an everyday task. If you want, you can write what it was below.'],options:[['try','Попробовал разобраться сам на практике','Tried to work it out by doing it'],['search','Поискал объяснение, инструкцию или пример','Looked for an explanation, instructions or an example'],['ask','Спросил человека','Asked someone'],['ai','Обратился к ИИ или чат-боту','Asked AI or a chatbot'],['plan','Разделил дело на небольшие шаги','Broke the task into small steps'],['later','Отложил на потом','Left it for later'],['stop','Решил не делать это','Decided not to do it'],['no_example','Не вспоминается такого случая','I cannot remember a time like that']]},
 {id:'less_familiar_action',type:'single',title:['Вспомни недавний случай, когда хотелось спросить о чём-то человека, с которым ты мало общаешься. Что ты сделал?','Think of a recent time when you wanted to ask something of a person you rarely talk to. What did you do?'],hint:['Например, в школе, магазине или онлайн. Возьми один случай для этого и следующего вопроса. Имя писать не нужно.','For example, at school, in a shop or online. Use one example for this question and the next. You do not need to give a name.'],options:[['voice','Спросил устно — лично или голосом онлайн','Asked by speaking, in person or online'],['text','Написал сообщение','Sent a message'],['help','Попросил другого человека помочь спросить','Asked someone else to help me ask'],['self','Нашёл ответ другим способом','Found the answer another way'],['pending','Пока не спросил, но ещё собираюсь','Have not asked yet, but still plan to'],['not_asked','Так и не спросил','Did not ask in the end'],['unneeded','Вопрос перестал быть нужен','No longer needed to ask'],['no_example','Не было такого случая или не помню','It did not happen or I cannot remember']]},
 {id:'less_familiar_factors',type:'multi',title:['Что из этого было в том же случае?','Which of these were true in that same situation?'],hint:['Можно выбрать несколько ответов — и то, что помогало, и то, что мешало. Отвечай про этот случай, а не про общение вообще.','You can choose more than one answer, including things that helped and things that made it harder. Think about this situation, not talking to people in general.'],options:[['clear','Знал, как сформулировать вопрос','Knew how to word my question'],['channel','Можно было спросить удобным для меня способом','Could ask in a way that suited me'],['busy','Человек был занят или недоступен','The person was busy or not available'],['words','Было трудно подобрать слова','Found it hard to choose the words'],['reaction','Волновался, как человек отреагирует','Felt worried about how the person would react'],['timing','Не понимал, когда лучше обратиться','Was not sure when to ask'],['easy','Ничего особенно не мешало','Nothing really made it difficult'],['no_example','Нет примера или не помню подробности','I do not have an example or cannot remember the details']]}
 ]
};
export const ninthBlock = {
 id:'small-activity-v1',version:1,
 label:['Блок 09 · Небольшая проба','Set 09 · A small activity'],
 title:['Что хотелось бы<br>попробовать?','What would you<br>like to try?'],
 intro:['Сегодня можно выбрать одно короткое занятие и, если захочется, попробовать его прямо здесь. Достаточно пары минут. Можно только ответить на четыре вопроса — выполнять занятие необязательно. Оценок и правильного выбора нет.','Today you can choose a short activity and, if you want, try it here. A couple of minutes is enough. You can just answer the four questions; doing the activity is optional. There are no marks or right choices.'],
 questions:[
 {id:'activity_choice',type:'single',title:['Какое из этих маленьких занятий ты бы сейчас выбрал?','Which of these small activities would you choose now?'],hint:['Выбери по интересу. Не нужно ничего устанавливать, искать в интернете или менять в настройках.','Choose what interests you. You do not need to install anything, search online or change any settings.'],options:[['compare','Сравнить: наушники А — 20 часов работы и 180 г; Б — 35 часов и 260 г. Какие выбрал бы для себя и почему?','Compare: headphones A last 20 hours and weigh 180 g; B last 35 hours and weigh 260 g. Which would you choose for yourself, and why?'],['investigate','Разобраться: игра тормозит. Что ты проверил бы первым и что эта проверка помогла бы узнать?','Investigate: a game is running slowly. What would you check first, and what could that check tell you?'],['design','Придумать: добавь одну возможность в знакомую игру. Что сможет делать игрок?','Design: add one feature to a game you know. What will the player be able to do?'],['explain','Объяснить: новичок не знает, с чего начать знакомую тебе игру. Напиши ему два коротких шага.','Explain: a new player does not know how to start a game you know. Write two short steps for them.'],['story','Сочинить: в игре появилась дверь, которой раньше не было. Придумай два предложения о том, что за ней.','Write a story: a door appears in a game where there was no door before. Write two sentences about what is behind it.'],['none','Сейчас ни одно не хочется','I do not feel like choosing any of these now']]},
 {id:'choice_reason',type:'multi',title:['Что повлияло на твой выбор?','What affected your choice?'],hint:['Речь о занятии, которое ты только что выбрал. Можно выбрать несколько причин.','Think of the activity you just chose. You can choose more than one reason.'],options:[['topic','Интересна сама тема','The topic interests me'],['process','Нравится такой способ думать или делать','I enjoy thinking or working in this way'],['familiar','Это знакомо, примерно знаю, что делать','It is familiar; I roughly know what to do'],['new','Захотелось попробовать что-то новое','I wanted to try something new'],['short','Показалось самым простым или коротким','It seemed the easiest or shortest'],['useful','Результат мог бы пригодиться','The result could be useful'],['no_choice','Не выбрал занятие','I did not choose an activity']]},
 {id:'trial_status',type:'single',title:['Хочешь попробовать выбранное занятие? Как получилось на этот момент?','Would you like to try your chosen activity? How far did you get?'],hint:['Если хочется, вернись к первому вопросу и попробуй выбранное задание. Можно написать результат в поле ниже или просто обдумать. Можно сразу выбрать «Не пробовал». Останавливаться можно в любой момент.','If you want, go back to the first question and try your chosen activity. You can write your result below or just think it through. You can also choose “I did not try it” straight away. You can stop at any time.'],options:[['done','Попробовал и закончил то, что хотел','I tried it and finished what I wanted to do'],['started','Попробовал немного и пока остановился','I tried a little and stopped for now'],['unclear','Хотел попробовать, но не понял, что делать','I wanted to try, but did not understand what to do'],['not_now','Не пробовал','I did not try it'],['no_choice','Не выбрал занятие','I did not choose an activity']]},
 {id:'start_support',type:'multi',title:['Что помогло бы тебе начать такое занятие — или уже помогло сейчас?','What would help you start an activity like this, or helped you just now?'],hint:['Можно выбрать несколько ответов. Это пожелания, а не обещание выполнить задание.','You can choose more than one answer. These are preferences, not a promise to do the activity.'],options:[['step','Понятный первый шаг','A clear first step'],['example','Один готовый пример','One finished example'],['time','Возможность самому выбрать время','Being able to choose when to start'],['small','Знать, что можно сделать совсем немного и остановиться','Knowing I can do a little and stop'],['together','Кто-то рядом, у кого можно уточнить','Someone nearby I can ask'],['quiet','Спокойное место без отвлечений','A quiet place without distractions'],['ready','Ничего дополнительно не нужно','I do not need anything else'],['uninterested','Сейчас не хочется заниматься этим','I do not feel like doing this now']]}
 ]
};
export const tenthBlock = {
 id:'game-idea-first-step-v1',version:1,
 label:['Блок 10 · Идея для игры','Set 10 · An idea for a game'],
 title:['От первого шага<br>к маленькой идее','From a first step<br>to a small idea'],
 intro:['Попробуем придумать одну возможность для знакомой игры. Пример: «Игрок сможет поставить метку, которую видят друзья, чтобы показать, куда идти». Это только пример, можно придумать совсем другое. Четыре вопроса; выполнять задание и писать текст необязательно.','Let’s try thinking of one feature for a game you know. Example: “The player can place a marker that friends can see, to show where to go.” This is only an example; your idea can be different. Four questions; doing the activity and writing text are optional.'],
 questions:[
 {id:'idea_direction',type:'single',title:['Вспомни знакомую игру. Что хотелось бы сделать в ней удобнее или интереснее?','Think of a game you know. What would you like to make easier or more interesting in it?'],hint:['Это первый шаг: выбери только одно направление. Саму возможность пока придумывать не нужно. Название игры можно написать ниже, если хочется.','This is the first step: choose just one area. You do not need to think of the feature yet. You can write the name of the game below if you want.'],options:[['navigate','Находить путь или нужное место','Finding the way or a place I need'],['together','Делать что-то вместе с другими игроками','Doing things with other players'],['create','Создавать или менять что-то своё','Creating or changing something of my own'],['learn','Понимать правила и осваивать игру','Understanding the rules and learning to play'],['challenge','Пробовать новые задачи или испытания','Trying new tasks or challenges'],['story','Исследовать мир или следить за историей','Exploring the world or following the story'],['none','Сейчас ничего не хочется менять','I do not want to change anything now'],['no_game','Не выбрал игру','I have not chosen a game']]},
 {id:'idea_attempt',type:'single',title:['Если хочется, придумай одну возможность. Что получилось на этот момент?','If you want, think of one feature. How far did you get?'],hint:['Можно закончить фразу в поле ниже или просто обдумать: «Игрок сможет…, чтобы…». Например: «Игрок сможет поставить метку для друзей, чтобы показать, куда идти». Одной простой идеи достаточно. Можно ничего не придумывать и идти дальше.','You can finish this sentence below or just think about it: “The player can…, to…”. For example: “The player can place a marker for friends, to show where to go.” One simple idea is enough. You can also move on without thinking of an idea.'],options:[['formed','Придумал одну возможность','I thought of one feature'],['partial','Появилась часть идеи, но пока не целиком','I have part of an idea, but not all of it yet'],['stuck','Попробовал, но идея пока не появилась','I tried, but have not thought of an idea yet'],['unclear','Не понял, что нужно придумать','I did not understand what kind of idea to think of'],['not_tried','Не пробовал','I did not try']]},
 {id:'support_effect',type:'single',title:['Помогли ли пример и первый шаг понять, с чего начать?','Did the example and the first step help you see how to start?'],hint:['Первый шаг — выбрать игру и направление изменения. Пример — метка для друзей. Можно оценить подсказки, даже если не выполнял задание.','The first step was choosing a game and an area to change. The example was a marker for friends. You can comment on these even if you did not do the activity.'],options:[['both','Да, помогли и пример, и первый шаг','Yes, both the example and the first step helped'],['example','Помог пример','The example helped'],['step','Помог первый шаг','The first step helped'],['already','И без них было понятно, с чего начать','I already knew how to start without them'],['unclear','Даже с ними непонятно, с чего начать','Even with them, I am not sure how to start'],['not_used','Не смотрел на подсказки или не могу оценить','I did not use the hints or cannot say']]},
 {id:'continue_preference',type:'single',title:['Что тебе хотелось бы дальше?','What would you like to do next?'],hint:['Это пожелание для следующего блока, а не обещание выполнить задание.','This is a preference for the next set, not a promise to do an activity.'],options:[['develop','Немного развить эту игровую идею','Develop this game idea a little further'],['another_game','Попробовать другую идею для игры','Try a different idea for a game'],['different','Попробовать занятие другого типа','Try a different kind of activity'],['questions','Пока только отвечать на вопросы без заданий','Just answer questions without activities for now'],['pause','Сделать паузу в блоках','Take a break from the sets']]}
 ]
};
export const eleventhBlock = {
 id:'helping-new-player-v1',version:1,
 label:['Блок 11 · Помощь новичку','Set 11 · Helping a new player'],
 title:['Что помогло бы<br>освоить игру?','What could help<br>someone learn a game?'],
 intro:['Четыре коротких вопроса о помощи новичку. Можно взять любую знакомую игру; вспоминать прошлую идею не нужно. Достаточно выбирать ответы. Если тема сейчас не интересна, можно пропустить вопросы.','Four short questions about helping a new player. You can use any game you know; you do not need to remember your earlier idea. Choosing answers is enough. If the topic does not interest you now, you can skip questions.'],
 questions:[
 {id:'new_player_difficulty',type:'single',title:['Представь новичка в знакомой тебе игре. С чем ему могла бы понадобиться помощь в начале?','Imagine a new player in a game you know. What might they need help with at the start?'],hint:['Выбери одну трудность для следующих двух вопросов. Это твоё предположение, проверять его сейчас не нужно. Название игры можно написать ниже, если хочется.','Choose one difficulty for the next two questions. This is your guess; you do not need to test it now. You can write the game’s name below if you want.'],options:[['goal','Понять, какая цель и что делать первым','Understanding the goal and what to do first'],['controls','Разобраться с управлением','Learning the controls'],['rules','Понять правило или игровую возможность','Understanding a rule or game feature'],['way','Найти нужное место или предмет','Finding a place or item'],['mistake','Понять, почему что-то не получается','Understanding why something is not working'],['people','Понять, как играть вместе с другими','Learning how to play with other people'],['none','Не вижу конкретной трудности','I cannot think of a particular difficulty'],['no_game','Не выбрал игру','I have not chosen a game']]},
 {id:'help_format',type:'single',title:['Какую помощь ты предложил бы для этой трудности?','What help would you suggest for that difficulty?'],hint:['Та же игра и та же трудность. Выбери один вариант, который хотелось бы попробовать первым.','Think of the same game and difficulty. Choose one option you would like to try first.'],options:[['demo','Короткий показ нужного действия','A short demonstration of the action'],['hint','Короткую подсказку словами','A short hint in words'],['practice','Безопасную тренировочную попытку','A safe practice attempt'],['person','Помощь другого игрока по ходу игры','Help from another player while playing'],['highlight','Выделить нужную кнопку, место или предмет','Highlighting the right button, place or item'],['choice','Дать новичку выбрать способ помощи','Letting the new player choose the kind of help'],['no_example','Нет выбранной трудности','I have not chosen a difficulty']]},
 {id:'help_check',type:'single',title:['По чему можно было бы понять, что эта помощь сработала?','How could you tell that this help worked?'],hint:['Это всё ещё твоя идея, проводить проверку не нужно. Здесь нет единственного правильного ответа.','This is still your idea; you do not need to test it. There is no single right answer.'],options:[['action','Новичок смог сам сделать нужное действие','The new player could do the action on their own'],['explain','Смог своими словами объяснить, что делать','They could explain what to do in their own words'],['less_stuck','Стал реже застревать в этом месте','They got stuck at that point less often'],['feedback','Сам сказал, что стало понятнее','They said it was clearer'],['next','Смог перейти к следующему шагу','They could move on to the next step'],['unsure','Пока не знаю, как это проверить','I do not know how to check yet'],['no_example','Нет выбранного примера','I have not chosen an example']]},
 {id:'topic_experience',type:'single',title:['Как тебе было выбирать ответы про помощь новичку?','What was it like choosing answers about helping a new player?'],hint:['Можно честно выбрать, что тема не заинтересовала. Это поможет подобрать следующие вопросы.','It is fine to say the topic did not interest you. This will help us choose the next questions.'],options:[['interesting','Было интересно, хотелось обдумывать варианты','It was interesting; I wanted to think about the options'],['easy','Выбирать было легко, но особого интереса не было','Choosing was easy, but I was not very interested'],['hard_interesting','Было интересно, но выбирать было трудно','It was interesting, but choosing was difficult'],['unclear','Было непонятно, что представить','I was not sure what to imagine'],['not_interested','Тема сейчас не заинтересовала','The topic did not interest me today'],['tired','Было трудно сосредоточиться или устал','I found it hard to focus or felt tired'],['skipped','Не отвечал на вопросы по этой теме','I did not answer the questions about this topic']]}
 ]
};
export const twelfthBlock = {
 id:'app-convenience-v1',version:1,
 label:['Блок 12 · Удобное приложение','Set 12 · An app that is easy to use'],
 title:['Что можно<br>сделать удобнее?','What could be<br>easier to use?'],
 intro:['Сегодня другая тема: приложение со списком дел. Например, крупный текст может помочь легче читать список. Ниже будет отдельная ситуация, где можно выбрать своё улучшение. Четыре вопроса; рисовать, устанавливать приложение и писать текст не нужно.','Today’s topic is a to-do list app. For example, larger text can make a list easier to read. Below is a different situation where you can choose an improvement. Four questions; you do not need to draw, install an app or write text.'],
 questions:[
 {id:'app_change',type:'single',title:['В приложении все дела идут одним длинным списком. Человек долго ищет дела на сегодня. Что ты попробовал бы изменить первым?','An app shows all tasks in one long list. It takes someone a long time to find today’s tasks. What would you try changing first?'],hint:['Первый шаг — выбрать одно изменение. Можно предложить своё в поле ниже, но это необязательно.','The first step is to choose one change. You can suggest your own below, but you do not have to.'],options:[['today','Добавить кнопку «Сегодня», которая показывает только сегодняшние дела','Add a “Today” button that shows only today’s tasks'],['group','Разделить список на группы по датам','Group the tasks by date'],['highlight','Выделить сегодняшние дела цветом и подписью','Mark today’s tasks with a colour and a label'],['pin','Поставить сегодняшние дела в начало списка','Move today’s tasks to the top'],['ask','Сначала уточнить у человека, как он ищет дела','First ask the person how they look for tasks'],['unchanged','Пока ничего не менять','Leave it as it is for now']]},
 {id:'app_check',type:'single',title:['Как ты проверил бы, что человеку стало удобнее?','How would you check whether it became easier for the person?'],hint:['Та же ситуация со списком дел. Это только выбор способа проверки — проводить её сейчас не нужно. Если сначала решил уточнить задачу, можно выбрать проверку на будущее.','Think of the same to-do list. Just choose a way to check; you do not need to do it now. If you chose to ask a question first, you can choose a check for later.'],options:[['time','Сравнить, сколько времени занимает поиск дел на сегодня до и после изменения','Compare how long it takes to find today’s tasks before and after the change'],['errors','Посмотреть, реже ли человек пропускает нужное дело или выбирает не то','See whether the person misses tasks or picks the wrong ones less often'],['feedback','Спросить, стало ли удобнее и почему','Ask whether it is easier and why'],['observe','Посмотреть, как он пользуется списком без подсказок','Watch how they use the list without hints'],['choose','Дать попробовать два варианта и выбрать удобный','Let them try two versions and choose one'],['unsure','Пока не знаю, как проверить','I do not know how to check yet']]},
 {id:'app_interest',type:'single',title:['Как тебе было обдумывать эту ситуацию с приложением?','What was it like thinking about this app situation?'],hint:['Можно выбрать, что тема не заинтересовала или ситуация была непонятна.','It is fine to say the topic did not interest you or the situation was unclear.'],options:[['interesting','Было интересно выбирать и обдумывать варианты','It was interesting to choose and think about the options'],['easy','Выбирать было легко, но особого интереса не было','Choosing was easy, but I was not very interested'],['hard_interesting','Было интересно, но выбрать было трудно','It was interesting, but choosing was difficult'],['unclear','Было трудно представить ситуацию','It was hard to imagine the situation'],['not_interested','Тема сейчас не заинтересовала','The topic did not interest me today'],['tired','Было трудно сосредоточиться или устал','I found it hard to focus or felt tired']]},
 {id:'topic_comparison',type:'single',title:['Какую из двух тем тебе было интереснее обдумывать?','Which of the two topics was more interesting to think about?'],hint:['В блоке 11 речь шла о помощи новичку освоить игру. Здесь — о поиске дел в приложении. Если прошлую тему не помнишь, сравнивать не нужно.','Set 11 was about helping a new player learn a game. This set was about finding tasks in an app. If you do not remember the earlier topic, you do not need to compare them.'],options:[['game','Помощь новичку в игре','Helping a new player in a game'],['app','Удобство приложения','Making an app easier to use'],['both','Обе были примерно одинаково интересны','Both were about equally interesting'],['neither','Ни одна особо не заинтересовала','Neither was very interesting'],['forgot','Не помню прошлую тему достаточно, чтобы сравнить','I do not remember the earlier topic well enough to compare']]}
 ]
};
export const thirteenthBlock = {
 id:'device-choice-and-start-v1',version:1,
 label:['Блок 13 · Выбирать и начинать','Set 13 · Choosing and starting'],
 title:['Что важно<br>при выборе?','What matters<br>when you choose?'],
 intro:['Три вопроса о сравнении устройств и один — об обычном деле. Это вымышленный выбор, покупать ничего не нужно. Достаточно выбрать ответы; писать текст необязательно.','Three questions about comparing devices and one about an everyday task. This is an imaginary choice; you do not need to buy anything. Choosing answers is enough; writing text is optional.'],
 questions:[
 {id:'device_choice',type:'single',title:['Представь, что выбираешь наушники для себя. Какой вариант тебе ближе?','Imagine choosing headphones for yourself. Which option would you prefer?'],hint:['Цена одинаковая. А: 180 г, 20 часов без зарядки. Б: 260 г, 35 часов без зарядки. Про звук и удобство посадки информации пока нет. Первый шаг — решить, хватает ли тебе этих данных для выбора.','The price is the same. A: 180 g, 20 hours per charge. B: 260 g, 35 hours per charge. There is no information about sound or fit yet. First, decide whether you have enough information to choose.'],options:[['a','А: легче, но меньше времени без зарядки','A: lighter, but less time per charge'],['b','Б: тяжелее, но дольше работают без зарядки','B: heavier, but more time per charge'],['more','Сначала хотел бы узнать больше или попробовать','I would want more information or to try them first'],['either','Оба варианта мне подходят','Either option would suit me'],['neither','Сейчас не хочется выбирать наушники','I do not feel like choosing headphones now']]},
 {id:'device_priority',type:'single',title:['Что для тебя важнее всего в этом выборе?','What matters most to you in this choice?'],hint:['Можно выбрать приоритет, даже если пока не выбрал наушники. Речь о твоих предпочтениях, правильного ответа нет.','You can choose a priority even if you have not chosen headphones yet. This is about your preferences; there is no right answer.'],options:[['weight','Небольшой вес','Low weight'],['battery','Реже заряжать','Charging less often'],['sound','Качество звука','Sound quality'],['fit','Насколько удобно сидят','How comfortable they feel'],['use','Подходят ли для того, как я буду ими пользоваться','Whether they suit how I would use them'],['balance','Баланс нескольких характеристик','A balance of several features'],['no_interest','Этот выбор мне неинтересен','This choice does not interest me']]},
 {id:'comparison_interest',type:'single',title:['Как тебе было сравнивать эти варианты?','What was it like comparing these options?'],hint:['Оцени само занятие, а не наушники.','Think about the activity, not the headphones themselves.'],options:[['interesting','Было интересно обдумывать различия','It was interesting to think about the differences'],['easy','Выбирать было легко, но особого интереса не было','Choosing was easy, but I was not very interested'],['hard_interesting','Было интересно, но трудно выбрать','It was interesting, but hard to choose'],['more_detail','Хотелось больше подробностей для сравнения','I wanted more details to compare'],['not_interested','Сравнивать было неинтересно','Comparing them was not interesting'],['unclear','Не понял, как их сравнить','I was not sure how to compare them']]},
 {id:'everyday_start',type:'multi',title:['Вспомни одно недавнее обычное дело, которое собирался сделать. Что влияло на начало?','Think of one recent everyday task you planned to do. What affected getting started?'],hint:['Например, собрать вещи, сделать школьное задание или ответить на сообщение. Выбери один случай, даже если дело так и не начал. Можно отметить несколько ответов. Если хочется, напиши ниже, что это было.','For example, packing your things, doing schoolwork or replying to a message. Choose one occasion, even if you never started. You can choose more than one answer. If you want, write what the task was below.'],options:[['clear','Было понятно, что делать первым, и это помогло','Knowing what to do first helped'],['time','Помогло самому выбрать время начала','Choosing when to start helped'],['reminder','Помогло напоминание или поддержка человека','A reminder or support from someone helped'],['unclear','Не было понятно, с чего начать','I was not sure where to start'],['switch','Было трудно оторваться от другого занятия','It was hard to stop another activity'],['energy','Не хватало сил или хотелось отдохнуть','I had little energy or wanted to rest'],['purpose','Не видел смысла или не хотелось делать это','I did not see the point or did not want to do it'],['waiting','Ждал нужной информации, вещи или человека','I was waiting for information, something I needed or a person'],['easy','Начал без особых затруднений','I started without much difficulty'],['no_example','Не вспоминается такого случая','I cannot remember an example']]}
 ]
};
export const fourteenthBlock = {
 id:'information-and-packing-v1',version:1,
 label:['Блок 14 · Выбор и сборы на завтра','Set 14 · Choosing and packing for tomorrow'],
 title:['Что помогает<br>перейти к делу?','What helps you<br>get started?'],
 intro:['Один вопрос о выборе наушников и три — о сборах вещей на следующий день. Для последних трёх вопросов возьми один недавний случай. Если такого случая не было или он не вспоминается, можно так и ответить. Писать текст необязательно.','One question about choosing headphones and three about packing things for the next day. Use one recent example for the last three questions. If it did not happen or you cannot remember, you can say so. Writing text is optional.'],
 questions:[
 {id:'headphone_information',type:'multi',title:['Что ты хотел бы узнать или проверить перед выбором этих наушников?','What would you want to find out or check before choosing these headphones?'],hint:['Ситуация из блока 13: цена одинаковая. А — 180 г и 20 часов без зарядки; Б — 260 г и 35 часов. Про звук и посадку данных нет. Можно выбрать несколько ответов; прошлый ответ вспоминать не нужно.','The situation from set 13: the price is the same. A weighs 180 g and lasts 20 hours per charge; B weighs 260 g and lasts 35 hours. There is no information about sound or fit. You can choose more than one answer; you do not need to remember your earlier answer.'],options:[['sound','Послушать, как звучат','Listen to how they sound'],['fit','Примерить, удобно ли сидят','Try them on to check the fit'],['connection','Узнать, подходят ли к моему устройству','Check whether they work with my device'],['microphone','Проверить микрофон','Test the microphone'],['reliability','Узнать о надёжности и опыте других людей','Find out how reliable they are and what other people say'],['use','Сначала решить, где и для чего буду использовать','First decide where and how I would use them'],['enough','Этих данных мне уже достаточно','I already have enough information'],['not_interested','Сейчас не хочется разбирать этот выбор','I do not feel like thinking about this choice now']]},
 {id:'packing_outcome',type:'single',title:['Вспомни недавний случай, когда собирался подготовить вещи на завтра. Как получилось?','Think of a recent time when you planned to get your things ready for the next day. What happened?'],hint:['Например, одежду, сумку или нужные предметы. Возьми один случай для этого и следующих двух вопросов. Не обязательно для школы.','For example, clothes, a bag or things you needed. Use one example for this question and the next two. It does not have to be for school.'],options:[['evening','Подготовил заранее, до следующего дня','Got them ready before the next day'],['morning','Подготовил уже на следующий день','Got them ready the next day'],['part','Подготовил часть вещей','Got some of the things ready'],['help','Вещи подготовили вместе или за меня','Someone helped get them ready or did it for me'],['not_done','Так и не подготовил','Did not get them ready'],['not_needed','Оказалось, что готовить вещи не нужно','It turned out I did not need to get anything ready'],['no_example','Такого случая не было или не помню','It did not happen or I cannot remember']]},
 {id:'packing_before',type:'multi',title:['Что происходило, когда ты думал начать собирать вещи?','What was happening when you were thinking about starting to pack?'],hint:['Тот же случай. Если не начал собираться, это тоже подходит. Можно выбрать несколько ответов.','Think of the same occasion. You can answer even if you did not start packing. You can choose more than one answer.'],options:[['activity','Был занят другим делом','I was busy doing something else'],['rest','Отдыхал или хотел отдохнуть','I was resting or wanted to rest'],['unclear','Не знал точно, что понадобится завтра','I was not sure what I would need the next day'],['later','Планировал собрать вещи позже','I planned to pack later'],['reminder','Кто-то напомнил о вещах','Someone reminded me about packing'],['started','Как подумал об этом, так и начал','I started as soon as I thought of it'],['forgot','Вспомнил о вещах уже на следующий день','I only remembered the next day'],['no_example','Нет примера или не помню этот момент','I do not have an example or cannot remember that moment']]},
 {id:'packing_factors',type:'multi',title:['Что в тот раз помогало или мешало начать?','What helped or made it harder to start that time?'],hint:['Отметь то, что было в этом случае, а не что обычно должно помогать. Можно выбрать несколько вариантов или написать свой.','Choose what was true on that occasion, not what should usually help. You can choose more than one answer or write your own.'],options:[['own_time','Помогло выбрать время самому','Choosing the time myself helped'],['finished','Помогло сначала закончить другое занятие','Finishing another activity first helped'],['clear','Помогло знать, что именно нужно собрать','Knowing exactly what to pack helped'],['support','Помогло напоминание или участие другого человека','A reminder or help from someone helped'],['switch','Мешало то, что не хотелось прерывать другое занятие','Not wanting to stop another activity made it harder'],['tired','Мешала усталость','Feeling tired made it harder'],['unclear','Мешало то, что было непонятно, что нужно собрать','Not knowing what to pack made it harder'],['no_need','Не видел необходимости готовить вещи заранее','I did not see a need to pack in advance'],['easy','Особой помощи не требовалось, затруднений не было','I did not need extra help and had no difficulty'],['no_example','Нет примера или не могу выделить причину','I do not have an example or cannot name a reason']]}
 ]
};
export const fifteenthBlock = {
 id:'switching-activities-v1',version:1,
 label:['Блок 15 · От одного дела к другому','Set 15 · Moving from one activity to another'],
 title:['Как получается<br>переключиться?','How do you move<br>to another activity?'],
 intro:['Четыре вопроса о переходе между занятиями. Первые два — о сборах вещей из блока 14. Последние два — о другом случае, когда нужно было прерваться. Если пример не вспоминается, не нужно угадывать. Писать текст необязательно.','Four questions about moving between activities. The first two are about packing from set 14. The last two are about another time when you needed to stop an activity. If you cannot remember an example, you do not need to guess. Writing text is optional.'],
 questions:[
 {id:'packing_transition',type:'single',title:['Как ты перешёл от другого занятия к сборам вещей в случае из блока 14?','How did you move from your other activity to packing in the example from set 14?'],hint:['Речь о том случае, когда готовил вещи на следующий день. Выбери вариант, который ближе к тому, как было.','Think of that time when you got your things ready for the next day. Choose the answer closest to what happened.'],options:[['finished','Закончил предыдущее занятие целиком, потом стал собираться','Finished the whole activity, then started packing'],['stopping_point','Дошёл до удобного места для остановки, потом стал собираться','Reached a good place to stop, then started packing'],['interrupted','Прервал занятие до удобного места и стал собираться','Stopped before a good stopping point and started packing'],['between','На тот момент уже ничем не был занят','Was no longer doing anything else at that point'],['different','Всё было иначе','It happened differently'],['forgot','Не помню тот случай','I do not remember that occasion']]},
 {id:'packing_thought',type:'single',title:['Когда в том случае появилась мысль, что пора собрать вещи?','When did you think it was time to pack on that occasion?'],hint:['Тот же случай. Вопрос только о последовательности событий, правильного порядка нет.','Think of the same occasion. This is only about the order of events; there is no right order.'],options:[['during','Ещё во время другого занятия','While I was still doing the other activity'],['ending','Когда уже заканчивал или дошёл до места для остановки','When I was finishing or had reached a stopping point'],['after','После того как перестал заниматься предыдущим делом','After I had stopped the other activity'],['reminder','Когда кто-то напомнил','When someone reminded me'],['planned','Я заранее решил, когда соберу вещи','I had already decided when to pack'],['forgot','Не помню или не могу разделить эти моменты','I do not remember or cannot separate these moments']]},
 {id:'interruption_action',type:'single',title:['Теперь вспомни другой недавний случай: нужно было перейти к делу, хотя предыдущее занятие ещё не закончилось. Что ты сделал?','Now think of another recent time: you needed to start a task before your previous activity was finished. What did you do?'],hint:['Например, пора было выходить, есть или делать что-то по договорённости. Возьми один случай для этого и следующего вопроса. Само занятие могло быть любым.','For example, it was time to leave, eat or do something you had agreed to do. Use one example for this question and the next. The activity could be anything.'],options:[['switched','Остановился и перешёл к нужному делу','Stopped and moved to the task'],['pause','Сохранил результат или поставил на паузу, потом перешёл','Saved my progress or paused, then moved to the task'],['asked_time','Попросил немного времени, потом перешёл','Asked for a little time, then moved to the task'],['finished','Сначала закончил занятие, потом перешёл','Finished the activity first, then moved to the task'],['stayed','Продолжил занятие, к другому делу не перешёл','Kept doing the activity and did not move to the other task'],['changed_plan','Договорился сделать другое дело позже','Agreed to do the other task later'],['no_example','Такого случая не было или не помню','It did not happen or I cannot remember']]},
 {id:'interruption_help',type:'multi',title:['Что помогло перейти к другому делу в этом случае?','What helped you move to the other task on that occasion?'],hint:['Отметь то, что действительно помогло тогда. Если не перешёл или ничего не помогло, это тоже можно выбрать. Можно отметить несколько ответов.','Choose what actually helped that time. You can also say that you did not switch or that nothing helped. You can choose more than one answer.'],options:[['notice','Знал заранее, когда понадобится остановиться','Knew in advance when I would need to stop'],['few_minutes','Было немного времени, чтобы закончить небольшой кусок','Had a little time to finish a small part'],['save','Можно было сохранить результат или поставить на паузу','Could save my progress or pause'],['return','Знал, когда смогу вернуться к занятию','Knew when I could return to the activity'],['reason','Понимал, почему другое дело нужно сделать сейчас','Understood why the other task needed doing now'],['step','Было понятно, что делать дальше','Knew what to do next'],['easy','Особая помощь не понадобилась','Did not need any particular help'],['nothing','Ничего не помогло или к другому делу не перешёл','Nothing helped or I did not move to the other task'],['no_example','Нет примера или не помню, что помогло','I do not have an example or cannot remember what helped']]}
 ]
};
export const block = {
 id:'learning-something-new-v1',version:1,
 label:['Блок 16 · Осваивать новое','Set 16 · Learning something new'],
 title:['Как ты разбираешься<br>в новом?','How do you learn<br>something new?'],
 intro:['Четыре вопроса об одном недавнем случае, когда ты учился делать что-то новое. Можно взять небольшой пример, не обязательно сложный или успешный. Вспоминать прошлые блоки не нужно. Писать текст необязательно.','Four questions about one recent time when you learned to do something new. It can be a small example; it does not have to be difficult or successful. You do not need to remember earlier sets. Writing text is optional.'],
 questions:[
 {id:'learning_example',type:'single',title:['Что новое ты недавно пробовал освоить?','What new thing did you recently try to learn?'],hint:['Выбери один случай для всего блока. Если хочется, напиши ниже, что именно это было. Если пример не вспоминается, можно так и ответить.','Choose one example for the whole set. If you want, write what it was below. If you cannot remember an example, you can say so.'],options:[['game','Правило, действие или способ прохождения в игре','A rule, action or way to get through part of a game'],['software','Функцию программы, приложения или устройства','A feature in a program, app or device'],['school','Способ решить учебную задачу','A way to solve a school task'],['language','Слово, выражение или правило другого языка','A word, phrase or rule in another language'],['creative','Что-то для создания рисунка, текста, музыки или другого проекта','Something for making a drawing, text, music or another project'],['daily','Обычное практическое дело вне компьютера','An everyday practical task away from a computer'],['no_example','Не вспоминается такого случая','I cannot remember an example']]},
 {id:'learning_first',type:'single',title:['С чего ты начал в этом случае?','What did you do first on that occasion?'],hint:['Тот же пример. Выбери первый способ, даже если потом использовал другие.','Think of the same example. Choose the first method, even if you used others later.'],options:[['try','Сразу попробовал разобраться на практике','Tried to work it out by doing it'],['watch','Посмотрел, как это делают, вживую или на видео','Watched someone do it in person or in a video'],['read','Прочитал объяснение или инструкцию','Read an explanation or instructions'],['person','Попросил человека объяснить или помочь сделать вместе','Asked someone to explain or help me do it together'],['ai','Попросил ИИ или чат-бот объяснить','Asked AI or a chatbot to explain'],['known','Попробовал применить то, что уже знал','Tried using something I already knew'],['not_started','Выбрал, чему хочу научиться, но пока не начал','Chose what I wanted to learn, but have not started yet'],['no_example','Нет примера или не помню начало','I do not have an example or cannot remember the start']]},
 {id:'learning_help',type:'multi',title:['Что действительно помогло разобраться в этом случае?','What actually helped you understand it on that occasion?'],hint:['Можно выбрать несколько ответов. Отметь то, что использовал тогда, а не то, что могло бы помочь вообще.','You can choose more than one answer. Choose what you used that time, not what might help in general.'],options:[['example','Увидеть готовый пример или показ действия','Seeing a finished example or a demonstration'],['steps','Идти по коротким понятным шагам','Following short, clear steps'],['experiment','Самому пробовать и видеть, что меняется','Trying things myself and seeing what changes'],['repeat','Вернуться к объяснению или повторить действие','Going back to the explanation or repeating the action'],['ask','Задать уточняющий вопрос и получить ответ','Asking a question and getting an answer'],['reason','Понять, почему это работает именно так','Understanding why it works that way'],['feedback','Увидеть ошибку или получить подсказку о ней','Noticing a mistake or getting a hint about it'],['nothing','Пока ничего не помогло','Nothing has helped yet'],['no_example','Нет примера или не могу выделить, что помогло','I do not have an example or cannot say what helped']]},
 {id:'learning_result',type:'single',title:['Что получилось к тому моменту, когда ты остановился?','What could you do by the time you stopped?'],hint:['Тот же случай. Можно ещё не закончить учиться или решить не продолжать — это тоже ответы.','Think of the same example. It is fine if you were still learning or decided not to continue.'],options:[['alone','Смог сделать нужное без подсказки','Could do what I wanted without a hint'],['supported','Смог сделать с примером, инструкцией или помощью рядом','Could do it with an example, instructions or help'],['part','Разобрался с частью, остались вопросы','Understood part of it, but still had questions'],['not_yet','Попробовал, но нужное пока не получилось','Tried, but could not do what I wanted yet'],['stopped','Решил не продолжать','Decided not to continue'],['not_started','Пока не пробовал','Have not tried yet'],['no_example','Нет примера или не помню результат','I do not have an example or cannot remember the result']]}
 ]
};
export const blocks = [firstBlock,secondBlock,thirdBlock,fourthBlock,fifthBlock,sixthBlock,seventhBlock,eighthBlock,ninthBlock,tenthBlock,eleventhBlock,twelfthBlock,thirteenthBlock,fourteenthBlock,fifteenthBlock,block];
